name: Create and post release

on:
  push:
    tags:
      - '*'
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          files: target/release/libvalida_cpf_cnpj.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
